my_string = input("Введите ФИО ")
print("Приветсвую ", my_string .upper())
print("Приветсвую ", my_string .lower())
print("Приветсвую ", my_string .replace(" ", "" ))
print("Приветсвую ", my_string [0])
print("Приветсвую ", my_string [-1])
